import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "../contexts/AuthContext";
import { NotificationProvider } from "../contexts/NotificationContext";
import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    display: "swap",
});

export const metadata: Metadata = {
    title: "XXAI",
    description: "Generated by create next app",
    icons: {
        icon: [{ url: "/qihanglogo.png" }, { url: "/favicon.ico" }],
        apple: "/qihanglogo.png",
        shortcut: "/qihanglogo.png",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={inter.className}>
            <head>
                <link rel="icon" href="/qihanglogo.png" />
                <link rel="shortcut icon" href="/qihanglogo.png" />
                <link rel="apple-touch-icon" href="/qihanglogo.png" />
            </head>
            <body className="antialiased w-full mx-auto h-full">
                <AuthProvider>
                    <NotificationProvider>{children}</NotificationProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
