debug: false

jwt:
    secret_key: "qihang-ai-jwt-token"
    algorithm: "HS256"
    access_token_expire_minutes: 30


postgresql:
    host: xx
    port: xx
    user: xx
    password: xx
    database: xx

clickhouse:
    host: xx
    port: 8123
    username: xx
    password: xx
    database: xx

logging:
    level: "DEBUG"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/qihang_ai.log"
    max_size: 10485760 # 10MB
    backup_count: 5
